dataset: P
node_num: 5
window_size: 10
max_thres: 2000
test_rate: 0.1
in_features: 1
out_features: 64
lstm_features: 128
disc_hidden: 512

batch_size: 64
gan_epoches: 300
gradient_clip: 5.0
weight_clip: 0.01
epsilon: 0.01

d_learning_rate: 0.00001
g_learning_rate: 0.00001
d_learning_rate_2: 0.000003
g_learning_rate_2: 0.000003
d_learning_rate_3: 0.000001
g_learning_rate_3: 0.000001